app/urls.py
from django.contrib import admin
from django.urls import path, include

from . import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sports.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sports/urls.py
from django.urls import path
from . import views

app_name='sports'

urlpatterns = [
    path('', views.index, name='index'),
    path('rules/<str:pk>/', views.rules, name='rules'),
    path('notables/<int:pk>/', views.notables, name='notables'),
    path('notables/<int:pk>/detail/<str:name>', views.playerDetail, name='player_detail'),
    path('links/<str:pk>/', views.links, name='links'),
]

sports/models.py
from django.db import models
from django.db.models.base import Model

# Create your models here.

class Sports(models.Model):
    name = models.CharField("スポーツ名", max_length=30)
    cover = models.ImageField("カバー写真", upload_to='sports/images', null=True, blank=True)
    rule = models.TextField("ルール")


    class Meta:
        verbose_name = "Sports"
        verbose_name_plural = "Sports"

    def __str__(self):
        return self.name


class Player(models.Model):
    name = models.CharField("選手名", max_length=30)
    picture = models.ImageField("プロフィール写真", upload_to='sports/images/profile', null=True, blank=True)
    description = models.TextField("選手説明")
    sports = models.ForeignKey(Sports, verbose_name="スポーツ名", on_delete=models.CASCADE)


    class Meta:
        verbose_name = 'Player'
        verbose_name_plural = 'Players'

    def __str__(self):
        return self.name

class Link(models.Model):
    title = models.CharField("タイトル", max_length=50, null=True)
    sports = models.ForeignKey(Sports, verbose_name="スポーツ", on_delete=models.CASCADE)
    link = models.URLField("関連記事", max_length=200)

    def __str__(self):
        return self.title

sports/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from .models import Sports, Player, Link
import random

# Create your views here.

def index(request):
    sports = Sports.objects.all()
    l = sports.count()
    randomPk = random.randint(1, l)
    # sport = sports.filter(pk=randomPk)
    sport = Sports.objects.get(pk=randomPk)

    context = {
        'sports': sport
    }
    return render(request, 'index.html', context)


def rules(request, pk):
    sport = get_object_or_404(Sports, pk=pk)
    context = {
        'sports': sport
    }
    return render(request, 'sports/rules.html', context)


def notables(request, pk):
    sport = get_object_or_404(Sports, pk=pk)
    players = get_list_or_404(Player, sports__name=sport.name)

    context = {
        'sports':sport,
        'players':players
    }
    return render(request, 'sports/notables.html', context)


def playerDetail(request, pk, name):
    sport = get_object_or_404(Sports, pk=pk)
    player = get_object_or_404(Player, name=name)
    print(player)
    context = {
        'sports': sport,
        'player': player
    }
    return render(request, "sports/detail.html", context)

def links(request, pk):
    sport = get_object_or_404(Sports, pk=pk)
    links = get_list_or_404(Link, sports__name=sport.name)

    context = {
        'sports': sport,
        'links':links
    }
    return render(request, 'sports/link.html', context)

templates/base.html
{% load static %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <title>Sports Fan website</title>
</head>
<body class="d-flex vh-100 text-center text-white bg-dark">
    <div class="cover-container d-flex w-100 h-100 mx-auto flex-column" style="background-image: url('{{ sports.cover.url }}'); background-size: cover; background-position: center 60%;">
        <div class="mask">
            <div class="container vh-100">
                {% include 'includes/base/nav.html' %}

                <main>
                    {% block main %}{% endblock %}
                </main>

                {% include 'includes/base/footer.html' %}
            </div>
        </div>

    </div>

    {% bootstrap_javascript %}
</body>
</html>

templates/includes/base/footer.html
<!-- <footer class="pt-5"> -->
    <!-- <div class="text-center p-2"> -->
        <!-- <span class="text-dark">@2021 sports fanwebsite all rights reserved</span> -->
    <!-- </div> -->
<!-- </footer> -->

<footer class="text-center mt-auto text-white-50 fixed-bottom">
    <p>@2021 sports fanwebsite all rights reserved.</p>
</footer>

templates/includes/base/nav.html
<header class="mb-auto">
    <div class="pt-3">
        <h3 class="float-md-start mb-0">Sports Fan Site</h3>
        <nav class="nav nav-masthead justify-content-center float-md-end">
            <a class="nav-link link-light active" aria-current="page" href="/">Home</a>
            <a class="nav-link link-light" href="{% url 'sports:rules' sports.id %}">Rule</a>
            <a class="nav-link link-light" href="{% url 'sports:notables' sports.id %}">Notables</a>
            <a class="nav-link link-light" href="{% url 'sports:links' sports.id %}">Link</a>
        </nav>
    </div>
</header>

templates/index.html
{% extends 'base.html' %}
{% load static %}



{% block main %}

    <div class="text-center">
        <div class="p-5"></div>
        <h1 class="pt-5 display-4 title">Fan Website</h1>

    </div>

{% endblock main %}

templates/sports/detail.html
{% extends 'base.html' %}
{% load static %}


{% block main %}
    <div class="pt-5">
        <h1>{{ player.name }}</h1>
        <div class="container mt-5">
            <div class="row">
                <div class="col-4">
                    <div class="card mx-auto" style="width: 18rem;">
                        <img src="{{ player.picture.url }}"  class="card-img-top" alt="{{ player.name }}">
                    </div>
                </div>
                <div class="col-8">
                    <div class="text-start">
                        <p>{{ player.description|linebreaksbr }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock main %}

templates/sports/link.html
{% extends 'base.html' %}
{% load static %}


{% block main %}
    <div class="pt-5">
        <h1>リンク集</h1>
        <div class="container">
            <div class="row">
                <div class="col-6 mx-auto">
                    <table class="table table-light mt-5">
                        <thead>
                        <tr>
                            <th scope="col">Link</th>
                        </tr>
                        </thead>
                        <tbody>

                            {% for link in links %}
                            <tr>
                                <td><a href="{{ link.link }}">{{ link.title }}</a></td>
                            </tr>
                            {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>

{% endblock main %}

templates/sports/notables.html
{% extends 'base.html' %}
{% load static %}


{% block main %}
    <div class="pt-5">
        <h1>選手紹介</h1>

        <div class="d-md-flex justify-content-between">
            {% for player in players %}
                <div class="card" style="width: 18rem;">
                    <img src="{{ player.picture.url }}"  class="card-img-top" alt="{{ player.name }}">
                    <div class="card-body">
                        <h5 class="card-title text-black">{{ player.name }}</h5>
                        <a href="{% url 'sports:player_detail' sports.pk player.name %}" class="btn btn-primary">詳細</a>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>

{% endblock main %}

templates/sports/rules.html
{% extends 'base.html' %}


{% block main %}
    <div class="pt-5">
        <h1 class="title">Rule</h1>
        <div class="container mt-5 px-5">
            <div class="row">
                <div class="col-8 mx-auto">
                    <p class="text-start">{{ sports.rule|linebreaksbr }}</p>
                </div>
            </div>
        </div>

    </div>

{% endblock main %}